version: '3.7'

services:
    mongodb-1:
        image: mongo:latest
        container_name: mongodb-1
        restart: always
        ports:
            - 37017:27017
        volumes:
            - ./mongodb.key:/data/mongodb.key
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123
        command: mongod --replSet mongoReplSet --keyFile /data/mongodb.key
        entrypoint:
            - bash
            - -c
            - |
              chmod 400 /data/mongodb.key
              chown 999:999 /data/mongodb.key
              exec docker-entrypoint.sh $$@
    mongodb-2:
        image: mongo:latest
        container_name: mongodb-2
        restart: always
        ports:
            - 37018:27017
        volumes:
            - ./mongodb.key:/data/mongodb.key
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123
        command: mongod --replSet mongoReplSet --keyFile /data/mongodb.key
        entrypoint:
            - bash
            - -c
            - |
              chmod 400 /data/mongodb.key
              chown 999:999 /data/mongodb.key
              exec docker-entrypoint.sh $$@
    mongodb-3:
        image: mongo:latest
        container_name: mongodb-3
        restart: always
        ports:
            - 37019:27017
        volumes:
            - ./mongodb.key:/data/mongodb.key
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123
        command: mongod --replSet mongoReplSet --keyFile /data/mongodb.key
        entrypoint:
            - bash
            - -c
            - |
                chmod 400 /data/mongodb.key
                chown 999:999 /data/mongodb.key
                exec docker-entrypoint.sh $$@
    mongodb-init:
        image: mongo:latest
        depends_on:
            - mongodb-1
            - mongodb-2
            - mongodb-3
        restart: on-failure:5
        command:                #这里一定要注意使用局域网ip或者外网ip 不要使用127.0.0.1或者localhost 
            - mongo
            - mongodb://root:123@192.168.0.103:37017/admin
            - --eval
            - 'rs.initiate({ _id: "mongoReplSet", members: [{_id:1,host:"192.168.0.103:37017"},{_id:2,host:"192.168.0.103:37018"},{_id:3,host:"192.168.0.103:37019"}]})'